Python Language Generation Tests
supabase/postgres-meta pull request #808
Opened 2024-10-01 19:17 UTC by ryanpeach

## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Does not generate python, 

## What is the new behavior?

Practicing TDD, designing tests first and asking the community for feedback.

## Additional Comments

I'd like everyones feedback on this format for the python types. I'm using pydantic and mimicing the go structure, since its closest to python dataclasses (basically structs).

2024-10-01 21:41 UTC, ryanpeach commented
I'm not really sure what a lot of these things other than "Tables" are. Materialized Views? Why are there different types for different operations? Composites?

2024-10-03 16:19 UTC, ryanpeach commented
I'd also like to do this again, but for rust.

2024-10-31 18:29 UTC, lwih commented
Man I'm looking forward to that :)

2024-11-14 02:27 UTC, yangcheng commented
happy to be early tester!

2024-11-21 20:55 UTC, ryanpeach commented
I've dropped my work on it atm if someone wants to take it the final mile, or wants to answer my questions on this pr, that would be great! Eventually i'll get back to working on supabase.

2024-12-16 01:09 UTC, ryanpeach commented
I need someone to check the tests. I’m know I’ve not covered all cases, but I don’t understand some of the test cases in the other code generators. Basically I need a code review.

2025-02-08 19:57 UTC, mikelong10 commented
Hey, y'all 👋 just wanted to join the convo here

I'm working on a project with a Next.js frontend, Python FastAPI backend, and Supabase, and recently realized there was no  python type gen support :(

I came across #795 when I was Googling around and then saw this PR here. Hoping to spark the convo and get the ball rolling again here! I did a quick look through, and the changes seem on the right track to me.

I'm def a little out of my domain here, but I saw @sweatybridge you commented on the original #795 saying you'd be more than happy to review a PR for this issue. Seems like @ryanpeach would love to get your or someone else from Supabase's eyes on this!

2025-02-11 13:21 UTC, grdsdev commented
Hi @ryanpeach, thanks a bunch for all the hard work you put into this PR!

I’d love to chat about this and figure out how we want to approach Python type generation. The way you implemented it, as raw Python models, sounds great, but we might want to take it a step further and try something more aligned with what we have in JS.

In `postgrest-js`, the generated types are integrated into the `PostgrestClient` as you can see on https://github.com/supabase/postgrest-js/blob/master/src/PostgrestClient.ts#L18-L24.

This makes types available during runtime usage of the library.

I’m not a Python expert, so I’m not sure how far Python types can go.

2025-02-11 15:19 UTC, ryanpeach commented
@grdsdev I did see that, but I think we should go for language availability before we go for complexity. That's why I emulated the go structs. Maybe all that can go in a V2.

2025-02-11 15:26 UTC, ryanpeach commented
Either way, I think the best solution is this:

1. Create a canonical "schema" for the database in TDD
2. Create an agreed upon "test" for the language generation in a PR. Evaluate it and vote on it.
3. Write the code to generate the test. Release.

2025-02-14 04:55 UTC, soedirgo commented
> we should go for language availability before we go for complexity. That's why I emulated the go structs

I'll have to disagree on this - the typegen needs to be well integrated into and narrowly scoped into the use case of the SDK. I don't see how generating structs/interfaces on its own would improve the Supabase DX.

I'd actually use the Go types as a reason against adding this, because to this day supabase-go still doesn't use the Go types (cmiiw), and it's not clear how you're meant to use the two together.

2025-02-14 05:00 UTC, soedirgo commented
To elaborate further: some of the reasons we added typings to supabase-js are because it affords us:
- autocompletion (table name in `.from()`, column name in filters)
- static type checking for missing columns in `.select()`
- typed result based on the query in `.select()`

I'm not convinced of the benefits of adding typings if it doesn't afford us these things.

2025-02-14 16:35 UTC, ryanpeach commented
@soedirgo you aren't convinced that having structs which match your tables, and having those structs autogenerated, is useful?

I'm sorry but I can't even begin to see the logic in that perspective... It's a basic serialization/deserialization paradigm. It's 1000x better than having an untyped object without data validation, static type checking, or IDE autocompletion.

And I think the interest in this issue is clear that people care about it. How many of the tools developed here ad-hoc by developers to fix this issue just for python go beyond struct generation?

2025-02-17 06:35 UTC, soedirgo commented
I see where you're coming from; if Python's typings doesn't support these features then it is what it is. I'll leave it to the supabase-py maintainers to decide if we want to add this in, because if we do want to add these features in v2 they'd be responsible for integrating the types with supabase-py. cc @juancarlospaco @silentworks @grdsdev

2025-02-17 06:42 UTC, soedirgo commented
What would also help is if you could show an example of how you'd use these types in your code, because certain approaches end up making the code much more verbose and it gets unclear whether it's a DX improvement or not (example [here](https://github.com/supabase/supabase-flutter/issues/139))

2025-02-17 22:29 UTC, ryanpeach commented
I'd just use pydantics deserialization and from dict capabilities after running a query, just to associate a type with the return and get data validation.

2025-02-18 10:07 UTC, silentworks commented
Great work here @ryanpeach. Can you provide a code example of how this would be used in a Python project?

2025-02-18 15:15 UTC, ryanpeach commented
```
import * from generated_table_classes

response = PublicUsersSelect(supabase.table("planets").select("*").execute())
```

2025-02-22 11:14 UTC, silentworks commented
I think this would be a great addition to the CLI for sure.

2025-02-27 17:41 UTC, mikelong10 commented
^ from testing locally, this seems to get the static type checking.

However, I will say that I have the "Mypy Type Checker" VSCode extension installed, and I don't believe by default Pydantic is able to catch the type errors of missing required fields in the `UsersInsert` class. For example, the Mypy extension picks this up, but if I disable the extension I don't get this red squiggly anymore:

<img width="830" alt="image" src="https://github.com/user-attachments/assets/6046f881-0519-46c8-885e-7a4c2df3d89c" />

Everything else seems good and working, though with intellisense picking up on it.

<img width="497" alt="image" src="https://github.com/user-attachments/assets/4221b835-c3a7-4409-8e72-81d8595d7203" />
<img width="384" alt="image" src="https://github.com/user-attachments/assets/726f9bbb-1def-4005-9fa0-95c7e53ce3c5" />
<img width="515" alt="image" src="https://github.com/user-attachments/assets/e9f24b10-6f48-48ef-941b-727a0c90f7d7" />
<img width="418" alt="image" src="https://github.com/user-attachments/assets/63d22117-c860-471d-ae29-bb809b8adf86" />

2025-03-04 08:58 UTC, ryanpeach commented
> Yeah I think this looks great! In terms of what's useful/valuable and would improve DX, I'd have to agree with @ryanpeach.
> 
> Essentially, even just simple auto-generated pydantic model classes that help you automatically stay up to date with your supabase schema and give you static type-checked, validated data to work with is enough of a DX improvement to make this effort worth it in my opinion 🙏
> 
> From your last example, maybe we could do this to make it even cleaner and clearer? Let me know your guys' thoughts and if you guys think something like this would be doable! cc: @silentworks
> ### Usage:
> 
> ```
> from generated_table_classes import Users, UsersInsert, UsersUpdate
> 
> insert_user_1 = Users.insert(UsersInsert(name="Ryan", email="ryan@gmail.com"))[0]
> insert_user_2 = Users.insert(UsersInsert(name="Mike"))[0]
> 
> select_user_1 = Users.select("*", filters={"id": insert_user_1.id})[0]
> select_all_users = Users.select("*")
> 
> update_user_1 = Users.update(
>     UsersUpdate(email="ryan@gmail.com"), filters={"id": insert_user_1.id}
> )[0]
> update_user_2 = Users.update(
>     UsersUpdate(name="Michael"), filters={"id": insert_user_2.id}
> )[0]
> ```
> 
> ### Implementation:
> 
> ```
> # generated_table_classes.py
> 
> # User schema, required name, optional email
> class User(BaseModel):
>     id: Annotated[int, Field(alias="id")]
>     name: Annotated[str, Field(alias="name")]
>     email: Annotated[str | None, Field(alias="email")] = None
> 
> 
> # UsersInsert schema, required name, optional email
> class UsersInsert(BaseModel):
>     name: Annotated[str, Field(alias="name")]
>     email: Annotated[str | None, Field(alias="email")] = None
> 
> 
> # UsersUpdate schema, optional name, optional email
> class UsersUpdate(BaseModel):
>     name: Annotated[str | None, Field(alias="name")] = None
>     email: Annotated[str | None, Field(alias="email")] = None
> 
> 
> # Single Users class used to interact with the users table
> class Users:
>     def __init__(self, users: list[dict]):
>         self.users = [User(**x) for x in users]
> 
>     def __iter__(self):
>         return iter(self.users)
> 
>     @staticmethod
>     def select(
>         *columns: str,
>         filters: Dict[str, Any] | None = None,
>         limit: int | None = None,
>         order_by: str | None = None,
>         descending: bool = True,
>     ) -> List[User]:
>         query = supabase.table("users").select(*columns)
> 
>         if filters:
>             for column, value in filters.items():
>                 if column == "or":
>                     query = query.or_(value)
>                 else:
>                     query = query.eq(column, value)
> 
>         if order_by:
>             query = query.order(order_by, desc=descending)
> 
>         if limit:
>             query = query.limit(limit)
> 
>         response = query.execute().data
>         return [User(**x) for x in response]
> 
>     @staticmethod
>     def insert(user: UsersInsert) -> List[User]:
>         response = supabase.table("users").insert(user.model_dump()).execute().data
>         return [User(**x) for x in response]
> 
>     @staticmethod
>     def update(
>         user: UsersUpdate,
>         filters: Dict[str, Any] | None = None,
>     ) -> List[User]:
>         query = supabase.table("users").update(user.model_dump())
>         if filters:
>             for column, value in filters.items():
>                 if column == "or":
>                     query = query.or_(value)
>                 else:
>                     query = query.eq(column, value)
> 
>         response = query.execute().data
>         return [User(**x) for x in response]
> ```

I think you need to keep it returning the Insert object and the Select object, otherwise you can't follow up with [filters](https://supabase.com/docs/reference/python/using-filters) and [modifiers](https://supabase.com/docs/reference/python/using-modifiers)

2025-05-09 05:16 UTC, MitchellGRead commented
curious if there is a reason this hasn't been merged yet?

2025-05-09 10:11 UTC, soedirgo commented
Just need to mark this PR as ready for review and a +1 from @silentworks, and then we can merge this.

2025-06-28 07:44 UTC, sourman commented
@ryanpeach thanks for the contribution! what help do you need to get this PR merged?

2025-08-05 00:15 UTC, ryanpeach commented
It's been a while, I will work on it again if I need a supabase project in the future, but I never got anyone to comment on the unit testing.

test/server/typegen.ts

If anyone officially with the project just would modify that test to make it look like the maintainers want it to look, then implementation is not difficult.

2025-10-07 18:18 UTC, Marviel commented
@silentworks -- per @soedirgo, any chance you could approve or request changes?

We're really hurting for python typed support.

EDIT: It looks like ryan needs feedback on his implementation.

@ryanpeach -- any specific points you're concerned about with impl that you'd want to discuss?

2025-11-11 14:51 UTC, o-santi requested changes
I've left a small review with some problems. I'll start working on these problems, and also on getting the code cleaned up so that it can be merged.

2025-11-11 14:51 UTC, o-santi commented on src/server/templates/python.ts
> +    )} \`json:"${name}"\``
Not correct. Seems to be related to golang struct generation?

2025-11-11 14:51 UTC, o-santi commented on src/server/templates/python.ts
> +  vector: 'list[Any]',
Ideally we should be able to infer which type of `vector` it is, and avoid using `Any`.

2025-11-11 14:51 UTC, o-santi commented on src/server/templates/python.ts
> +  jsonb: 'Json[Any]',
Is this correct? `pydantic.Json` is for string serialized JSON, to automatically parse it when reading. I guess this might be correct if when `model_validate`'ing the string.

2025-11-11 14:51 UTC, o-santi commented on src/server/templates/python.ts
> +  record: 'dict[str, Any]',
Can't we infer more than just `Any`?

2025-11-11 14:51 UTC, o-santi commented on src/server/templates/python.ts
> +    return nullable ? `${pythonType} | None` : pythonType
Not python 3.9 compatible. We intend to drop compatibility with it soon as 3.9 has reached EOL, but for the time being we might want to use `Optional` instead.

2026-09-07 16:48 UTC, avallete commented
Thanks for this. Type generation has moved out of `postgres-meta`: since v0.99.0 this repo consumes [`@supabase/postgrest-typegen`](https://github.com/supabase/sdk/tree/main/packages/postgrest-typegen) and the templates this PR added to were deleted in #1084.

Python generation already lives in that package (the current maintainer template, not this 2023 draft). The generators there are frozen for now — they are being relocated into each language's own SDK repository. Closing here as the target code no longer exists.

2026-09-07 16:48 UTC, closed without merging